### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by wrought** [nerdsfornature/nerdsfornature.github.com#1]
Need a unique-ish layout for our landing page, what do we want users to do? Sign up for the mailing list? See most recent news or events? Some other action?

**Comment by danrademacher** [comment]
There's already a home page template in place. I just went ahead and put in some of the copy we have on the home page and made an about page. Still need to add more bios there.

But probably the most important thing we need is the upcoming events and some sort of signup. For now I added a button to push people to Twitter
