### ISSUE TITLE
add OG tags for better sharability

### ISSUE THREAD

**Issue by danrademacher** [nerdsfornature/nerdsfornature.github.com#5]

**Comment by adriancotter** [comment]
added some to various pages, but facebook debugger seems to have some issues with the site. regardless of where I changed a page https://developers.facebook.com/tools/debug/og/object/ is returning this error:
"Error parsing input URL, no data was cached, or no data was scraped."

Problem with our DNS? (see issue here about CNAME and A for www?)
https://www.adminlabs.com/blog/solved-facebook-doesnt-fetch-data-when-sharing-url

**Comment by kueda** [comment]
The debug tool is parsing the page ok for me, but you might want to add the open graph prefix and/or namespace to the html tag of the page with open graph meta tags, e.g. `<html prefix="og: http://ogp.me/ns#">`
